name: CI Pipeline

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Runs on pull requests targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Set up the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from your requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover  # You can replace this with your preferred test command
