name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Ensures repository files are available

      - name: Verify requirements file exists
        run: ls -l web-socket  # Debug: List files in 'web-socket' directory

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r web-socket/requirements.txt  # Use correct path
